name: Execute Hlasovani notebook

on:
  push:
    branches:
      - main
    paths:
      - 'notebooks/**.src.ipynb'
      - 'parlamentikon/**.py'
      - '.github/workflows/**.yml'
  schedule:
    - cron: 0 3 * * *

jobs:
  run-notebooks:
    name: Run Jupyter notebooks for Parlamentikon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      # Install dependencies
      - name: Create venv and install requirements
        run: python3 -m venv venv && source venv/bin/activate && pip install wheel && pip install jupyter &&  pip install -r requirements.txt

      # Run the analytical notebooks
      - name: Run Analytics
        run: source venv/bin/activate && cd notebooks/ && jupyter nbconvert --to notebook --execute Hlasovani.src.ipynb --output Hlasovani.ipynb && jupyter nbconvert --to html Hlasovani.ipynb --output ../docs/Hlasovani.html
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add notebooks/Hlasovani.ipynb docs/Hlasovani.html
          git commit -m "Daily run of Hlasovani [github-actions, bot]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
